on:
  schedule:
    - cron: "0 2 * * 1,5"
  workflow_dispatch:

name: Docker images

jobs:
  build-images:
    name: Build & push Docker images
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      
    strategy:
      matrix:
        runtime:
          - name: freedesktop+rust-24.08
            packages: org.freedesktop.Platform//24.08 org.freedesktop.Sdk//24.08 org.freedesktop.Sdk.Extension.rust-stable//24.08
            
    services:
      registry:
        image: registry:latest
        ports:
          - 5000:5000

    steps:
      - name: Checkout
        uses: actions/checkout@4.2.2

      - name: Set up Docker Buildx
        # 3.10.0
        uses: docker/setup-buildx-action@3.10.0
        with:
          driver-opts: network=host

      - name: Build & push the base image to local registry
        # 6.15.0
        uses: docker/build-push-action@6.16.0
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          pull: true
          push: true
          tags: localhost:5000/base:latest

      - name: Login to ghcr.io
        # 3.4.0
        uses: docker/login-action@3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Write the Dockerfile for the ${{ matrix.runtime.name }} runtime
        run: |
          cat >> ${{ matrix.runtime.name }}.Dockerfile << EOF
          # syntax = docker/dockerfile:experimental
          FROM localhost:5000/base:latest
          RUN --security=insecure flatpak install -y --noninteractive ${{matrix.runtime.remote}} ${{ matrix.runtime.packages }}

      - name: Build & push the ${{ matrix.runtime.name }} image
        # 6.15.0
        uses: docker/build-push-action@6.16.0
        with:
          allow: security.insecure
          context: .
          file: ${{ matrix.runtime.name }}.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/klassenserver7b/flatpak-github-actions-rust:${{ matrix.runtime.name }}

  test_actions:
    needs:
    - build-images
    uses: ./.github/workflows/test.yml
